import {
  IconLayoutDashboard, IconPencilPlus, IconList, IconSettings,
  IconX, IconChevronDown, IconClock, IconMapPin, IconReceipt,
  IconCamera, IconPhoto, IconSearch,
  IconCar, IconToolsKitchen, IconWifi, IconTruckDelivery, IconPackage,
  IconShield, IconTool, IconPrinter, IconBulb, IconPlane, IconDots,
  IconCash, IconGift, IconFolders, IconUserCog, IconLogout,
  IconUser, IconShare,
  IconMail, IconLock, IconEye, IconEyeOff,
  IconCheck, IconArrowLeft, IconArrowRight, IconChevronLeft, IconChevronRight,
  IconPlus, IconHandStop, IconFileInvoice,
  IconHome, IconShoppingCart, IconDeviceMobile, IconBolt, IconBike,
  IconBus, IconTrain, IconShip, IconBuildingStore, IconBuildingHospital,
  IconSchool, IconBooks, IconDeviceLaptop, IconHeadphones, IconShirt,
  IconHeart, IconBabyCarriage, IconPaw, IconPlant, IconCoffee,
  IconBottle, IconPigMoney, IconCreditCard, IconWallet, IconCoin,
  IconTicket, IconMovie, IconMusic, IconRun,
  IconSwimming, IconBarbell, IconDog, IconCat, IconTrees,
  IconDroplet, IconFlame, IconWind, IconCloud, IconSun,
  IconMoon, IconUmbrella, IconBackpack, IconShoe, IconGlassFull,
  IconFirstAidKit, IconStethoscope, IconVaccine, IconPill,
} from '@tabler/icons-react';
// Icon name → component map (used for category icons from DB)
export const iconMap: Record<string, any> = {
  car: IconCar,
  utensils: IconToolsKitchen,
  wifi: IconWifi,
  truck: IconTruckDelivery,
  package: IconPackage,
  shield: IconShield,
  tool: IconTool,
  printer: IconPrinter,
  bulb: IconBulb,
  plane: IconPlane,
  dots: IconDots,
  cash: IconCash,
  gift: IconGift,
  receipt: IconReceipt,
  'hand-loan': IconHandStop,
  home: IconHome,
  shopping: IconShoppingCart,
  mobile: IconDeviceMobile,
  bolt: IconBolt,
  bike: IconBike,
  bus: IconBus,
  train: IconTrain,
  ship: IconShip,
  store: IconBuildingStore,
  hospital: IconBuildingHospital,
  school: IconSchool,
  books: IconBooks,
  laptop: IconDeviceLaptop,
  headphones: IconHeadphones,
  shirt: IconShirt,
  heart: IconHeart,
  baby: IconBabyCarriage,
  paw: IconPaw,
  plant: IconPlant,
  coffee: IconCoffee,
  bottle: IconBottle,
  'pig-money': IconPigMoney,
  'credit-card': IconCreditCard,
  wallet: IconWallet,
  coin: IconCoin,
  ticket: IconTicket,
  movie: IconMovie,
  music: IconMusic,
  sport: IconRun,
  run: IconRun,
  swim: IconSwimming,
  gym: IconBarbell,
  dog: IconDog,
  cat: IconCat,
  tree: IconTrees,
  water: IconDroplet,
  fire: IconFlame,
  wind: IconWind,
  cloud: IconCloud,
  sun: IconSun,
  moon: IconMoon,
  umbrella: IconUmbrella,
  backpack: IconBackpack,
  shoe: IconShoe,
  drink: IconGlassFull,
  'first-aid': IconFirstAidKit,
  medical: IconStethoscope,
  vaccine: IconVaccine,
  pill: IconPill,
};

// Render a category icon by name, fallback to emoji
export function CatIcon({ name, size = 16 }: { name: string; size?: number }) {
  const Icon = iconMap[name];
  if (Icon) return <Icon size={size} stroke={1.5} />;
  return <span style={{ fontSize: size }}>{name || '📌'}</span>;
}

// Named exports for direct use
export {
  IconLayoutDashboard, IconPencilPlus, IconList, IconSettings,
  IconX, IconChevronDown, IconClock, IconMapPin, IconReceipt,
  IconCamera, IconPhoto, IconSearch,
  IconFolders, IconUserCog, IconLogout,
  IconUser, IconShare,
  IconMail, IconLock, IconEye, IconEyeOff, IconWallet,
  IconCheck, IconArrowLeft, IconArrowRight,
  IconChevronLeft, IconChevronRight, IconPlus, IconFileInvoice,
};
